server:
  port: "8081"
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DEPARTMENT_DB_NAME:departmentdb}
    username: ${MYSQL_DB_USERNAME:demo}
    password: ${MYSQL_DB_PASSWORD:rahul}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}    